spring.application.name=springsecurity

#These password and username will be ignored if you have defined your own custom roles and password in securityConfig
spring.security.user.password = Rishi@123
spring.security.user.name = admin
